version: '3.8'

services:
  deployment-pipeline:
    build: .
    ports:
      - "3001:3001"
      - "5173:5173"
    environment:
      - NODE_ENV=development
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  # For Docker-in-Docker
      - ./:/app
      - /tmp:/tmp
    env_file:
      - .env
    command: npm run dev

  # Redis for job queuing (optional)
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  # Optional: Database for storing deployment history
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: deployments
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: